version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory

      - run:
          name: Install dependencies with yarn
          command: yarn

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: yarn test # replace with `yarn test` if using yarn
  build_master:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
            - run: GITHUB_TOKEN=$GITHUB_TOKEN yarn release

workflows:
  version: 2
  Build and Test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
  build_master:
    jobs:
      - build_master:
          filters:
            branches:
              only:
                - master

