version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
            - run: GITHUB_TOKEN=$GITHUB_TOKEN yarn release

local_workflow: &local_workflow
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/

production_workflow: &production_workflow
  filters:
    branches:
      only: master         

workflows:
    build-and-test:
      jobs:
        - build-and-test:
          <<: *local_workflow
    production:
      jobs:
        - deploy:
          <<: *production_workflow

